Numpy(Numerical Python) is a fundamental package for scientifc computing with Python,provides support for arrays, matrices and a large collection of mathematical functions to operate on these data structures

Numpy arrays are more efficient and have better performance for numerical operations compared to Python's built in lists.

Array Object in NumpPy is called ndArray.

In [3]:
pip install numpy

In [6]:
import numpy as np

In [7]:
#Creating numpy array from list

arr1=np.array([1,2,3,4,5])
print(arr1)

#2d array
arr2=np.array([[1,2,3],[4,5,6]])  #each element is a 1D array
print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [8]:
arr3=np.array(['a','b'])
print(arr3)

['a' 'b']


Creating Arrays with functions

In [9]:
#Creating an array with zero

zero_array=np.zeros((2,3))
print(zero_array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
one_array=np.ones((2,3))
print(one_array)

[[1. 1. 1.]
 [1. 1. 1.]]


In [14]:
#Creating an array with a range of values
range_arr=np.arange(1,10,2) #arange(start,stop,step)
print(range_arr)

[1 3 5 7 9]


In [16]:
random_arr=np.random.rand(2,2)  # 0 to 1 float numbers ( 2 rows, 2 cols)
print(random_arr)

[[0.75855615 0.5448122 ]
 [0.93292296 0.25439625]]


Basic Array Operations- Element wise Operations

In [21]:
arr=np.array([1,2,3,4,5])
print(arr[0])
print(arr + 2 )
print(arr[1:3])

1
[3 4 5 6 7]
[2 3]


In [22]:
for i in arr:
  print(i)

1
2
3
4
5


In [25]:
print("Square of the array: ", arr*arr)

Square of the array:  [ 1  4  9 16 25]


Mathematical Functions

In [28]:
print(np.sqrt(arr))
print(np.exp(arr))
print(np.log(arr))
print(np.sin(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


** Indexing and Slicing **

In [40]:
print(arr[-1:-6:-1])
print(arr[:-3:-1])

[5 4 3 2 1]
[5 4]


Advanced Indexing

In [43]:
print(arr[arr > 3]) #Boolean Indexing

 #Fancy indexing
indices=[1,4,3]
print(arr[indices])

[4 5]
[2 5 4]


Resahping and Transposing - Reshaping Arrays

In [48]:
arr= np.array([[1,2,3],[4,5,6]])
print(arr)
reshaped = arr.reshape(1,6) #reshape(rows*col)
print(reshaped)

[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5 6]]


Transposing

In [50]:
arr= np.array([[1,2,3],[4,5,6]])
transpose=arr.T
print(transpose)

[[1 4]
 [2 5]
 [3 6]]


Aggregation Function - Sum and Mean

In [52]:
arr= np.array([[1,2,3],[4,5,6]])
print(np.sum(arr))

21


In [54]:
#Sum along Columns
print(np.sum(arr,axis=0))

#sum along rows
print(np.sum(arr,axis=1))

[5 7 9]
[ 6 15]


In [56]:
print(np.mean(arr))
print(np.mean(arr,axis=1))

3.5
[2. 5.]


In [59]:
print(np.min(arr))
print(np.min(arr,axis=1))

1
[1 4]


In [61]:
#index of min value

print(np.argmin(arr))
print(np.argmax(arr))

0
5
